#include <inttypes.h>

int main(void)
{
    uint8_t *addr;

    /*
     * Third 2MB chunk in the second 1GB block.
     * See .mte_page section in kernel.ld.
     */
    addr = (void *)((1UL << 30) | (1UL << 22));

    asm (
        /*
         * Set GCR for randon tag generation. 0xA5 is just a random value to set
         * GCR != 0 so the tag generated by 'irg' is not zero.
         */
        "ldr x1, =0xA5;"
        "msr gcr_el1, x1;"

         /* Generate a logical tag and put it in 'addr' pointer. */
         "irg %[addr], %[addr];"

         /*
          * Store the generated tag to memory region pointed to by 'addr', i.e.
          * set the allocation tag for the memory region.
          */
         "stg %[addr], [%[addr]];"

         /*
          * Store a random value (0xdeadbeef) to *addr. This must not cause any
          * Tag Check Fault since logical and allocation tags are set the same.
          */
	 "ldr x1, =0xdeadbeef;"
	 "str x1, [x0];"
         : [addr] "+r" (addr)
         :
         :
    );
}
